"""This only runs on belltown/sodo, a Sage Bionetworks cluster.

"""

import os
import csv

# For running synapse client, which requires python 2
# PY2VIRTENV = "/home/ubuntu/.virtualenvs/python2.7/bin/activate"
PY2VIRTENV = "/home/kdaily/.virtualenvs/synpydev/bin/activate"

SAMPLE_FILE = list(csv.DictReader(open("./input/sample_table.csv")))
# SAMPLE_FILE = SAMPLE_FILE[:50]

SAMPLE_DICT = dict([(x["UID"], x) for x in SAMPLE_FILE])

FASTQ_DIR = "/external-data/DAT_114__PCBC_Data/mRNA/fastq/"

def get_filename(wildcards):
    try:
        filename = SAMPLE_DICT[wildcards[0]]['fileName']
    except Exception as e:
        print(e)
        print(wildcards)
        raise(e)
    
    return filename

def get_synid(wildcards):
    try:
        synid = SAMPLE_DICT[wildcards[0]]['id']
    except Exception as e:
        print(e)
        print(wildcards)
        raise(e)
    
    return synid

def get_sample_info(wildcards):
    try:
        info = SAMPLE_DICT[wildcards[0]]
    except Exception as e:
        print(e)
        print(wildcards)
        raise(e)
    
    return info

rule all:
     input: expand('./output/bowtie/{sample}.txt', sample=SAMPLE_DICT.keys())
     
rule bowtie:
    input: './input/samples/{sample}.txt'
    output: './output/bowtie/{sample}.txt'
    params: batch='-l nodes=1',python2virtenv=PY2VIRTENV,sample='{sample}',fastqdir=FASTQ_DIR,synid=get_synid,filename=get_filename
    threads: 4
    shell: """source {params.python2virtenv}; \
                    	      
              ## Do the work
	      ls -l {params.fastqdir}/{params.filename} > {output} ; \
              deactivate ; \
           """
	    
