"""This only runs on belltown/sodo, a Sage Bionetworks cluster.

"""

import os
import csv

# For running synapse client, which requires python 2
PY2VIRTENV = "%s/.virtualenvs/python2/bin/activate" % os.environ['HOME']

SAMPLE_FILE = list(csv.DictReader(open("./input/sample_table.csv")))
SAMPLE_FILE = SAMPLE_FILE[:1]

SAMPLE_DICT = dict([(x["UID"], x) for x in SAMPLE_FILE])

def get_mapped_synid(wildcards):
    try:
        synid = SAMPLE_DICT[wildcards[0]]['bam_mapped']
    except Exception as e:
        print(e)
        print(wildcards)
        raise(e)

    return synid

def get_unmapped_synid(wildcards):
    try:
        synid = SAMPLE_DICT[wildcards[0]]['bam_unmapped']
    except Exception as e:
        print(e)
        print(wildcards)
        raise(e)

    return synid

rule all:
     input: expand('output/{uid}.txt', uid=SAMPLE_DICT.keys())

rule process:
    input: './input/samples/{uid}.txt'
    output: final="output/{uid}.txt"
    params: batch='-pe orte 1',python2virtenv=PY2VIRTENV,uid='{uid}',mapped_bam=get_mapped_synid,scratchdir="/tmp",unmapped_bam=get_unmapped_synid
    threads: 8
    shell: """## setup
         mkdir -p {params.scratchdir}/{params.uid}/ ; \

         # Get files from synapse
	     source {params.python2virtenv}; \
         synapse get {params.mapped_bam} --downloadLocation {params.scratchdir}/{params.uid}/ ; \
         synapse get {params.unmapped_bam} --downloadLocation {params.scratchdir}/{params.uid}/ ; \
    	 deactivate ; \

         # Index
         samtools index {params.scratchdir}/{params.uid}/{params.uid}.bam ; \
         samtools index {params.scratchdir}/{params.uid}/unmapped.bam ; \

	     # Count pass qc primary mapped reads
         samtools view -F 0x300 {params.scratchdir}/{params.uid}/{params.uid}.bam | wc -l > {params.scratchdir}/{params.uid}/mapped.txt ; \

         # Count pass qc primary unmapped reads
         samtools view -f 0x4 -F 0x300 {params.scratchdir}/{params.uid}/unmapped.bam | wc -l > {params.scratchdir}/{params.uid}/unmapped.txt ; \

         # Together
         paste -d, {params.scratchdir}/{params.uid}/mapped.txt {params.scratchdir}/{params.uid}/unmapped.txt > {params.scratchdir}/{params.uid}/both.txt ; \

         # Write stuff out
         echo "UID,mapped,unmapped,total" > {output.final} ; \

         awk -F',' '{{sum = $1 + $2; print "{params.uid},"$1","$2","sum}}' {params.scratchdir}/{params.uid}/both.txt >> {output.final} ; \

	     ## cleanup
	     # rm -rf {params.scratchdir}/{params.uid}/

         """
