```{r}
library(synapseClient)
library(plyr)
library(dplyr)
library(data.table)
library(stringr)
library(tidyr)
library(reshape2)
library(ComplexHeatmap)
synapseLogin()

compNames <- synTableQuery("SELECT * FROM syn4483642")@values

# Takes data and clusters cols
diffStateClusterFxn <- function(x) {
  tmp <- dcast(x, UID ~ GeneSymbol, value.var = "value")
  d <- dist(tmp, method = "euclidean")
  hclust(d, method="average")
}

# Reorders based on clustering
diffStateReorderFxn <- function(x, metadata, clusterings) {
  foo <- metadata %>% filter(Diffname_short == x)
  foo$o <-as.numeric(clusterings[[x]]$order)
  foo %>% arrange(o) %>% select(-o)  
}

# Diff states in a sensible, quasi time-based ordering
orderedDiffState <- c("SC", "EB", "DE", "MESO-5", "MESO-15", "MESO-30", "ECTO")

```

```{r readdegenesdata_mrna}
obj <- synGet("syn4484232")
d <- fread(getFileLocation(obj), data.table=FALSE)

# Filter out the comparisons we're interested in
# And significance levels as well
d2 <- d %>% 
  rename(comparison=Comparison) %>%
  filter(abs(logFC) > 2,
         adj.P.value < 0.0001,
         str_detect(comparison, "^All__")) %>%
  mutate(direction=str_extract(comparison, "__.*"),
         direction=str_replace(direction, ".*__", ""),
         comparison=str_replace(comparison, "__up", ""),
         comparison=str_replace(comparison, "__down", "")) %>%
  left_join(compNames) %>%
  filter(class == "Diffname_short")
```

```{r readmetadata_mrna}
metadata <- synTableQuery("select * from syn3156503")@values %>%
  filter(Diffname_short != "") %>%
  filter(Cell_Type == "PSC") %>%  
  filter(pass_qc == "TRUE") %>%
  filter(exclude != "TRUE") %>%
  filter(C4_Karyotype_Result != "abnormal")
```

```{r despecificgenes_mrna}
# Find diff state specific genes
res <- llply(unique(d2$variable1),
             function(x) setdiff(filter(d2, variable1 == x)$GeneSymbol, 
                                 filter(d2, variable1 != x)$GeneSymbol))

names(res) <- unique(d2$variable1)
diffstateSpecificGenes <- ldply(res, function(x) data.frame(GeneSymbol=x), .id="diffstate")
```

```{r keepgenes_mrna}
# Keep genes
keepGenes <- diffstateSpecificGenes
```

```{r getcountdata_mrna}
countObj <- synGet("syn4483934")

countData <- fread(getFileLocation((countObj)), data.table=FALSE) %>%
  rename(GeneSymbol=GeneName) %>%
  filter(GeneSymbol %in% d2$GeneSymbol)

rownames(countData) <- countData$GeneSymbol

existingUIDs <- intersect(colnames(countData), metadata$UID)

metadata <- metadata %>% filter(UID %in% existingUIDs)

countData <- countData %>% select(GeneSymbol, one_of(metadata$UID))

countData2 <- countData
rownames(countData2) <- countData2$GeneSymbol

# assayData <- as.matrix(countData[, -1])
# phenoData <- metadata
# rownames(phenoData) <- metadata$UID
# 
# eset <- ExpressionSet(assayData=assayData,
#                       phenoData=AnnotatedDataFrame(phenoData),
#                       featureData=AnnotatedDataFrame(countData[, c("GeneSymbol"), drop=F]))

```

```{r cluster_mRNA}
countData3 <- melt(countData2, id.vars = "GeneSymbol") %>%
  rename(UID=variable) %>% left_join(metadata[, c("UID", "Diffname_short")])

clusterings <- dlply(countData3, .(Diffname_short), diffStateClusterFxn)

metadataReordered <- ldply(orderedDiffState, 
                           diffStateReorderFxn, 
                           metadata=metadata, clusterings=clusterings)

countMat <- countData2[, -1]
countMat <- scale(countMat)
countMat <- t(scale(t(countMat)))

countMat <- countMat[, metadataReordered$UID]

```

```{r plot_mrna}
dfAnnotations <- metadataReordered %>% 
  rename(DiffState=Diffname_short) %>%
  select(DiffState)

samplesAnnotation <- HeatmapAnnotation(df=dfAnnotations,
                                       col=list(DiffState=c("EB"="red", "ECTO"="blue", 
                                                            "SC"="orange", "DE"="yellow",
                                                            "MESO-5"="black", 
                                                            "MESO-15"="green",
                                                            "MESO-30"="pink")))

pdf('SuppFig1_mRNA.pdf')
ht <- Heatmap(countMat, name = "log10(Expression)", 
              # col = colorRamp2(c(-2, 0, 2), c("blue", "white", "red")),
              show_row_names = FALSE, 
              show_column_names = FALSE,
              # row_names_gp = gpar(fontsize = 8),
              # column_names_gp = gpar(fontsize = 8),
              cluster_rows = TRUE,
              cluster_columns = FALSE,
              clustering_method_rows = "average",
              clustering_method_columns = "average",
              show_row_hclust = FALSE, 
              show_column_hclust = FALSE, 
              top_annotation = samplesAnnotation)

print(ht)
dev.off()

```

```{r readdegenesdata_mirna}
obj <- synGet("syn4609631")
d <- fread(getFileLocation(obj), data.table=FALSE)

# Filter out the comparisons we're interested in
# And significance levels as well
d2 <- d %>% 
  rename(comparison=Comparison) %>%
  filter(abs(logFC) > 2,
         adj.P.value < 0.0001,
         str_detect(comparison, "^All__")) %>%
  mutate(direction=str_extract(comparison, "__.*"),
         direction=str_replace(direction, ".*__", ""),
         comparison=str_replace(comparison, "__up", ""),
         comparison=str_replace(comparison, "__down", "")) %>%
  left_join(compNames) %>%
  filter(class == "Diffname_short")
```

```{r readmetadata_mirna}
metadata <- synTableQuery("select * from syn3219876")@values %>%
  filter(Diffname_short != "") %>%
  filter(Cell_Type == "PSC") %>%  
  filter(pass_qc == "TRUE") %>%
  filter(exclude != "TRUE") %>%
  filter(C4_Karyotype_Result != "abnormal")
```

```{r getcountdata_mirna}
countObj <- synGet("syn3355993")

countData <- fread(getFileLocation((countObj)), data.table=FALSE) %>%
  rename(GeneSymbol=id) %>%
  filter(GeneSymbol %in% d2$GeneSymbol)

existingUIDs <- intersect(colnames(countData), metadata$UID)

metadata <- metadata %>% filter(UID %in% existingUIDs)

countData <- countData %>%
  dplyr::select(one_of(c("GeneSymbol", metadata$UID)))

countData2 <- countData
rownames(countData2) <- countData2$GeneSymbol

countData2[, -1] <- log10(countData2[, -1] + 0.001)

```

```{r cluster_mirna}
countData3 <- melt(countData2, id.vars = "GeneSymbol") %>%
  rename(UID=variable) %>% left_join(metadata[, c("UID", "Diffname_short")])

clusterings <- dlply(countData3, .(Diffname_short), diffStateClusterFxn)

metadataReordered <- ldply(orderedDiffState, 
                           diffStateReorderFxn, 
                           metadata=metadata, clusterings=clusterings)

countMat <- countData2[, -1]
countMat <- scale(countMat)
countMat <- t(scale(t(countMat)))

countMat <- countMat[, metadataReordered$UID]

```

```{r plot_mirna}
dfAnnotations <- metadataReordered %>% 
  rename(DiffState=Diffname_short) %>%
  select(DiffState)

samplesAnnotation <- HeatmapAnnotation(df=dfAnnotations,
                                       col=list(DiffState=c("EB"="red", "ECTO"="blue", 
                                                            "SC"="orange", "DE"="yellow",
                                                            "MESO-5"="black", 
                                                            "MESO-15"="green",
                                                            "MESO-30"="pink")))

pdf('SuppFig1_miRNA.pdf')
ht <- Heatmap(countMat, name = "log10(Expression)", 
              # col = colorRamp2(c(-2, 0, 2), c("blue", "white", "red")),
              show_row_names = FALSE, 
              show_column_names = FALSE,
              # row_names_gp = gpar(fontsize = 8),
              # column_names_gp = gpar(fontsize = 8),
              cluster_rows = TRUE,
              cluster_columns = FALSE,
              clustering_method_rows = "average",
              clustering_method_columns = "average",
              show_row_hclust = FALSE, 
              show_column_hclust = FALSE, 
              top_annotation = samplesAnnotation)

print(ht)
dev.off()

```

```{r readdegenesdata_methylation}
obj <- synGet("syn4527629")
d <- fread(getFileLocation(obj), data.table=FALSE)

# Filter out the comparisons we're interested in
# And significance levels as well
d2 <- d %>% 
  rename(GeneSymbol=methProbeIDs, comparison=Comparison) %>%
  filter(abs(logFC) > 0.5,
         adj.P.value < 0.0001,
         str_detect(comparison, "^All__")) %>%
  mutate(direction=str_extract(comparison, "__.*"),
         direction=str_replace(direction, ".*__", ""),
         comparison=str_replace(comparison, "__up", ""),
         comparison=str_replace(comparison, "__down", "")) %>%
  left_join(compNames) %>%
  filter(class == "Diffname_short")
```

```{r readmetadata_methylation}
metadata <- synTableQuery("select * from syn3156828")@values %>%
  filter(Diffname_short != "") %>%
  filter(Cell_Type == "PSC") %>%  
  filter(C4_Karyotype_Result != "abnormal")
```

```{r getbetadata_methylation}
countObj <- synGet("syn4487642")

countData <- fread(getFileLocation((countObj)), data.table=FALSE) %>%
  rename(GeneSymbol=methProbeID) %>%
  filter(GeneSymbol %in% d2$GeneSymbol)

existingUIDs <- intersect(colnames(countData), metadata$UID)

metadata <- metadata %>% filter(UID %in% existingUIDs)

countData <- countData %>%
  dplyr::select(one_of(c("GeneSymbol", metadata$UID)))

countData2 <- countData
rownames(countData2) <- countData2$GeneSymbol

# countData2[, -1] <- log10(countData2[, -1] + 0.001)

```

```{r cluster_methylation}
countData3 <- melt(countData2, id.vars = "GeneSymbol") %>%
  rename(UID=variable) %>% left_join(metadata[, c("UID", "Diffname_short")])

clusterings <- dlply(countData3, .(Diffname_short), diffStateClusterFxn)

metadataReordered <- ldply(orderedDiffState, 
                           diffStateReorderFxn, 
                           metadata=metadata, clusterings=clusterings)

countMat <- countData2[, -1]
countMat <- scale(countMat)
countMat <- t(scale(t(countMat)))

countMat <- countMat[, metadataReordered$UID]

```

```{r plot_methylation}
dfAnnotations <- metadataReordered %>% 
  rename(DiffState=Diffname_short) %>%
  select(DiffState)

samplesAnnotation <- HeatmapAnnotation(df=dfAnnotations,
                                       col=list(DiffState=c("EB"="red", "ECTO"="blue", 
                                                            "SC"="orange", "DE"="yellow",
                                                            "MESO-5"="black", 
                                                            "MESO-15"="green",
                                                            "MESO-30"="pink")))

pdf('SuppFig1_methylation.pdf')
ht <- Heatmap(countMat, name = "log10(Expression)", 
              # col = colorRamp2(c(-2, 0, 2), c("blue", "white", "red")),
              show_row_names = FALSE, 
              show_column_names = FALSE,
              # row_names_gp = gpar(fontsize = 8),
              # column_names_gp = gpar(fontsize = 8),
              cluster_rows = TRUE,
              cluster_columns = FALSE,
              clustering_method_rows = "average",
              clustering_method_columns = "average",
              show_row_hclust = FALSE, 
              show_column_hclust = FALSE, 
              top_annotation = samplesAnnotation)

print(ht)
dev.off()

```